version: '3'
services:
  skauttrebic-frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:cached
    stdin_open: true
    tty: true
    environment:
    - HOST=0.0.0.0
    - CHOKIDAR_USEPOLLING=true
    ports:
    - 3000:3000